name: domo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    # for the google fonts: nunito
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2771.0
  flutter_animated_icons: ^1.0.1
  # for the liquid swipe on the onboarding screen
  liquid_swipe: ^3.1.0
  # for the smooth page indicator
  smooth_page_indicator: ^1.2.0+3
  # for the google sign in
  google_sign_in: ^6.2.1
  # for the pincode boxes
  pin_code_fields: ^8.0.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.3
  # for getxcontrollers
  get: ^4.6.6
  # for the firebase auth
  flutter_launcher_icons: "^0.13.1"
  cloud_firestore: ^5.2.0
  image_picker: ^1.1.2
  firebase_storage: ^12.1.2
  geolocator: ^12.0.0
  uuid: ^4.4.2
  shimmer: ^3.0.0
  url_launcher: ^6.1.10
  # for notifications
  flutter_local_notifications: ^17.2.1+2
  # firebase_messaging: ^15.0.4
  path_provider: ^2.1.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: tru
  image_path: "assets/images/D.png"

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/images/onboard/


